# Generated by Django 5.1.7 on 2025-04-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position_vacancy_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='position',
        ),
    ]
