# Generated by Django 5.1.7 on 2025-04-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_vacancy_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
