# Generated by Django 5.1.7 on 2025-04-02 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.position'),
            preserve_default=False,
        ),
    ]
